### ISSUE TITLE
snapshot show no data

### ISSUE THREAD

**Issue by fatehsinghji** [X-Wei/flutter_catalog#13]
while i am clonning the app, snaphot always show no data and ProgressIndicator always pops up.

**Comment by X-Wei** [comment]
Are you referring to the "chat room" demo ? 
For that one you have to create your own firebase project and generate your own json file, c.f. the [comment](https://github.com/X-Wei/flutter_catalog/blob/master/lib/routes/firebase_chatroom_ex.dart#L9-L11) in that file.

Background: I have configured my firebase project to only handle requests sent from apks built on certain computers. Because otherwise other can use up my firebase free quota.
