### ISSUE TITLE
Monetization Tab Bug

### ISSUE THREAD

**Issue by skj-skj** [X-Wei/flutter_catalog#135]
1. Code is not Syntax Highlighted except "Rewarded Ads"
2. Not able to view code of "Bottom banner ads".

**Comment by X-Wei** [comment]
Oh thanks for being so prompt to test it!

>1.Code is not Syntax Highlighted except "Rewarded Ads"
Thanks, it's due to a mistake in the file path, will be fixed in the next release.

>2.Not able to view code of "Bottom banner ads".
Yep, I know this issue, and it will be fixed with the v3.0 version of widget_with_codeview: see [this commit](https://github.com/X-Wei/widget_with_codeview/commit/aa749b576d8494f1e267ecb2bda3f933734445dd)

TLDR: wait for an update in the next a few days! :)

**Comment by X-Wei** [comment]
fixed in v3.3.0

**Comment by skj-skj** [comment]
Thanks for fixing this fast.
