### ISSUE TITLE
Build Fails! Help please.

### ISSUE THREAD

**Issue by Amber052829** [X-Wei/flutter_catalog#17]
Launching lib/main.dart on SM N960F in debug mode...
Initializing gradle...
Resolving dependencies...
 * Error running Gradle:
ProcessException: Process "/Users/amber052829/Downloads/flutter_catalog-master/android/gradlew" exited abnormally:
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/amber052829/Downloads/flutter_catalog-master/android/app/build.gradle' line: 61

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Command: /Users/amber052829/Downloads/flutter_catalog-master/android/gradlew app:properties

**Comment by Amber052829** [comment]
Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by Amber052829** [comment]
<img width="1680" alt="Screenshot 2019-05-11 at 7 10 58 PM" src="https://user-images.githubusercontent.com/20811024/57570519-86272a80-7420-11e9-8240-5722fac07237.png">
urgent help required.

**Comment by X-Wei** [comment]
According to the error message, it's [this line](https://github.com/X-Wei/flutter_catalog/blob/master/android/app/build.gradle#L61) that is failing, and it's because the "key.properties" file is explicitly [removed](https://github.com/X-Wei/flutter_catalog/blob/master/.gitignore#L2) by me since I don't want to reveal my apk signing keystore.

So you should create a file "flutter_catalog-master/android/key.properties", c.f. https://flutter.dev/docs/deployment/android#signing-the-app
