### ISSUE TITLE
App crashing on clicking 'go home' button 

### ISSUE THREAD

**Issue by kamlesh1687** [X-Wei/flutter_catalog#64]
In Navigation/routes section , their is a go home button in the last page(need to navigate to last page ) ,on clicking the
![Screenshot_20201127-182206](https://user-images.githubusercontent.com/38773749/100451461-7abc5280-30dd-11eb-9bd5-dd73d2edd950.jpg)
 app crashes and black screen appear.

**Comment by X-Wei** [comment]
Thanks for reporting & nice catch!
This is because I [depend on](https://github.com/X-Wei/flutter_catalog/blob/v2.5.0/lib/my_route.dart#L43) `widget.runtimeType` to determine their route names, but meanwhile I used `--obfuscate` flag when building the apk and this caused a name mismatch. (Cf. https://flutter.dev/docs/deployment/obfuscate#caveat)

I will fix this in the next app release.

**Comment by kamlesh1687** [comment]
Okay sure, Thanks.
